#!/bin/bash

# Setup .env file from Firebase project
# Usage: ./scripts/setup-env.sh

echo "🔥 Firebase Environment Setup"
echo "=============================="

# Check if firebase-tools is installed
if ! command -v firebase &> /dev/null; then
    echo "❌ Firebase CLI not found. Install it with: npm install -g firebase-tools"
    exit 1
fi

# Check if user is logged in
if ! firebase projects:list &> /dev/null; then
    echo "🔐 Please login to Firebase first:"
    firebase login
fi

# Get project ID
read -p "📝 Enter your Firebase Project ID (or press Enter to use current): " PROJECT_ID

if [ -z "$PROJECT_ID" ]; then
    # Try to get from .firebaserc
    if [ -f ".firebaserc" ]; then
        PROJECT_ID=$(cat .firebaserc | grep -o '"default": "[^"]*' | cut -d'"' -f4)
        echo "✓ Using project: $PROJECT_ID"
    else
        echo "❌ No .firebaserc found and no project ID provided"
        exit 1
    fi
fi

echo ""
echo "📡 Fetching Firebase configuration from $PROJECT_ID..."
echo ""

# Create temporary file with Firebase config
TEMP_CONFIG=$(firebase apps:sdkconfig WEB --project=$PROJECT_ID 2>/dev/null || echo "")

if [ -z "$TEMP_CONFIG" ]; then
    echo "❌ Could not fetch Firebase config. Make sure:"
    echo "   1. Project ID is correct"
    echo "   2. You're logged in to Firebase"
    echo "   3. You have at least one Web app in the project"
    exit 1
fi

# Extract values from config
API_KEY=$(echo "$TEMP_CONFIG" | grep -o '"apiKey":"[^"]*' | cut -d'"' -f4)
AUTH_DOMAIN=$(echo "$TEMP_CONFIG" | grep -o '"authDomain":"[^"]*' | cut -d'"' -f4)
DATABASE_URL=$(echo "$TEMP_CONFIG" | grep -o '"databaseURL":"[^"]*' | cut -d'"' -f4)
STORAGE_BUCKET=$(echo "$TEMP_CONFIG" | grep -o '"storageBucket":"[^"]*' | cut -d'"' -f4)
MESSAGING_SENDER_ID=$(echo "$TEMP_CONFIG" | grep -o '"messagingSenderId":"[^"]*' | cut -d'"' -f4)
APP_ID=$(echo "$TEMP_CONFIG" | grep -o '"appId":"[^"]*' | cut -d'"' -f4)

# Create .env file
cat > .env << EOF
# Environment Variables Configuration
# Generated by setup-env.sh script

# Firebase Configuration
EXPO_PUBLIC_FIREBASE_API_KEY=$API_KEY
EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN
EXPO_PUBLIC_FIREBASE_DATABASE_URL=$DATABASE_URL
EXPO_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID
EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET
EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
EXPO_PUBLIC_FIREBASE_APP_ID=$APP_ID

# Google Gemini AI API Key
# Get your API key from: https://makersuite.google.com/app/apikey
EXPO_PUBLIC_GEMINI_API_KEY=

# Google Speech-to-Text API Key
# Get your API key from: https://console.cloud.google.com/apis/credentials
EXPO_PUBLIC_GOOGLE_SPEECH_API_KEY=

# Automatic SMS Configuration (for SOS alerts)
# Set these in Firebase Cloud Function environment variables (firebase functions:config:set)
# TWILIO_ACCOUNT_SID=
# TWILIO_AUTH_TOKEN=
# TWILIO_PHONE_NUMBER=

# App Configuration
EXPO_PUBLIC_APP_ENV=development
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "📋 Firebase values populated:"
echo "   ✓ API Key"
echo "   ✓ Auth Domain: $AUTH_DOMAIN"
echo "   ✓ Database URL"
echo "   ✓ Project ID: $PROJECT_ID"
echo "   ✓ Storage Bucket: $STORAGE_BUCKET"
echo "   ✓ Messaging Sender ID"
echo "   ✓ App ID"
echo ""
echo "⚠️  Still need to add manually:"
echo "   • EXPO_PUBLIC_GOOGLE_SPEECH_API_KEY (from Google Cloud Console)"
echo "   • EXPO_PUBLIC_GEMINI_API_KEY (from Google Gemini)"
echo ""
echo "🎉 Setup complete! Edit .env to add remaining values."
