apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.sosmodule'
version = '1.0.0'

buildscript {
  def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
  if (expoModulesCorePlugin.exists()) {
    apply from: expoModulesCorePlugin
    applyKotlinExpoModulesCorePlugin()
  }
}

android {
  compileSdkVersion safeExtGet("compileSdkVersion", 34)
  namespace "expo.modules.sosmodule"
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 21)
    targetSdkVersion safeExtGet("targetSdkVersion", 34)
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:\${safeExtGet('kotlinVersion', '1.8.10')}"
}
