apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.sosmodule'
version = '1.0.0'

android {
  compileSdkVersion rootProject.ext.has("compileSdkVersion") ? rootProject.ext.get("compileSdkVersion") : 34
  namespace "expo.modules.sosmodule"
  defaultConfig {
    minSdkVersion rootProject.ext.has("minSdkVersion") ? rootProject.ext.get("minSdkVersion") : 24
    targetSdkVersion rootProject.ext.has("targetSdkVersion") ? rootProject.ext.get("targetSdkVersion") : 34
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}
